permalink: /:year/:month/:day/:title.html
paginate: 20
markdown: redcarpet

# 作者信息
author: 
  name: horse
  email: equusprobus@gmail.com
  link: 
  weibo: 
  github: 
  music:
  linkedin: 

# 站点信息
title: 自由而无用的灵魂
description: My personal blog
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/me/horse.png
favicon: /public/img/me/horse.png

# google analytics 设置
ga:
  id: UA-65276774-1
  url: http://equusprobus.github.io/

# disqus 设置
disqus:
  shortname: equusprobus

# 主题设置，自动激活某个标签
active: 生活

# 首页除了最新文章外显示分类
# cates: 
#  - Optimization
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
